# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "EE292D: Machine learning on Embedded Systems"
email: keyi@cs.stanford.edu
course-info: >- # this means to ignore newlines until "baseurl:"
    <p>
    This is a project-based class where students will learn how to build modern connected embedded systems
    that utilize machine learning. The class briefly covers how to create embedded systems to cloud services
    and dives into details of how to do edge and cloud-based machine learning on time-series and image data.
    In the final project students are expected to produce a working system that improves the state of machine
    learning on the edge or solves a useful task by combining many different connected components.
    </p>
    <p>
    This class <b>will not</b> focus on several very import low-level aspects of embedded systems such as memory footprints,
    temperature resilience, etc.
    </p>
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

footer_text:
    Website maintained by Zain Asgar and Keyi Zhang.

# Build settings
markdown: kramdown
theme: minima
# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

